backend:
  name: git-gateway
  branch: master

display_url: https://dentondesign.netlify.com

slug:
  encoding: "ascii"
  clean_accents: true

media_folder: "static/images"
public_folder: "/images"

collections:
  - label: 'Settings'
    name: 'settings'
    editor:
      preview: false
    files:
      - label: Menu
        name: 'menu'
        file: 'static/content/menu.json'
        extension: json
        fields:
          - label: Links
            name: links
            widget: object
            fields:
              - label: Work
                name: work
                widget: object
                fields:
                - {label: Label, name: label, widget: string}
                - {label: Image, name: image, widget: image}
              - label: About
                name: about
                widget: object
                fields:
                - {label: Label, name: label, widget: string}
                - {label: Image, name: image, widget: image}
              - label: Contact
                name: contact
                widget: object
                fields:
                - {label: Label, name: label, widget: string}
                - {label: Image, name: image, widget: image}
      - label: Navbar
        name: navbar
        file: 'static/content/navbar.json'
        extension: json
        fields:
          - label: Logos
            name: logos
            widget: object
            fields:
              - label: Small
                name: small
                widget: object
                fields:
                - {label: Image, name: src, widget: image}
                - {label: Alt Text, name: alt, widget: string}
              - label: Desktop
                name: desktop
                widget: object
                fields:
                - {label: Image, name: src, widget: image}
                - {label: Alt Text, name: alt, widget: string}
      
  - label: 'Landing Pages'
    name: 'pages'
    editor:
      preview: false
    files:
      - label: Home
        name: 'home'
        file: 'static/content/home.json'
        extension: json
        fields:
          - label: Meta
            name: meta
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Image, name: image, widget: image}
          - label: Background Image
            name: backgroundImage
            widget: object
            fields:
            - {label: Image, name: src, widget: image}
            - {label: Alt Text, name: alt, widget: string}
          - label: Bold Page Title Text
            name: titleImage
            widget: object
            fields:
            - {label: Image, name: src, widget: image}
            - {label: Alt Text, name: alt, widget: string}
          - label: Caption
            name: caption
            widget: string
          - label: Explore
            name: explore
            widget: object
            fields:
              - {label: Label, name: label, widget: string}
              - label: Links
                name: links
                widget: list
                fields:
                - {label: Label, name: label, widget: string}
                - {label: URL, name: url, widget: string}
      
      - label: Work
        name: work
        file: 'static/content/work.json'
        extension: json
        fields:
          - label: Meta
            name: meta
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Image, name: image, widget: image}
          - label: Background Image
            name: backgroundImage
            widget: object
            fields:
            - {label: Image, name: src, widget: image}
            - {label: Alt Text, name: alt, widget: string}
          - label: Bold Page Title Text
            name: titleImage
            widget: object
            fields:
            - {label: Image, name: src, widget: image}
            - {label: Alt Text, name: alt, widget: string}
          - label: Links
            name: links
            widget: list
            fields:
            - {label: Label, name: label, widget: string}
            - {label: URL, name: url, widget: string}

      - label: About
        name: 'about'
        file: 'static/content/about.json'
        extension: json
        fields:
          - label: Meta
            name: meta
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Image, name: image, widget: image}
          - label: Background Image
            name: backgroundImage
            widget: object
            fields:
            - {label: Image, name: src, widget: image}
            - {label: Alt Text, name: alt, widget: string}
          - label: Bold Page Title Text
            name: titleImage
            widget: object
            fields:
            - {label: Image, name: src, widget: image}
            - {label: Alt Text, name: alt, widget: string}
          - label: Approach
            name: approach
            widget: object
            fields:
            - {label: Label, name: label, widget: string}
            - label: Content
              name: content
              widget: markdown
              buttons:
              - heading-two
              - bold
              - italic
              - link
            - label: Contact
              name: contact
              widget: object
              fields:
              - {label: Caption, name: caption, widget: string}
              - label: Link
                name: link
                widget: object
                fields:
                - {label: Label, name: label, widget: string}
                - {label: URL, name: url, widget: string}
          - label: Timeline
            name: timeline
            widget: object
            fields:
              - {label: Label, name: label, widget: string}
              - label: Top Text
                name: brownEvent
                widget: object
                fields:
                - {label: Years, name: years, widget: string}
                - {label: Title, name: title, widget: string}
                - {label: Content, name: content, widget: text}
              - label: Events
                name: events
                allow_add: true
                widget: list
                fields:
                - {label: Years, name: years, widget: string}
                - {label: Title, name: title, widget: string}
                - label: Content
                  name: content
                  widget: markdown
                  buttons:
                  - heading-two
                  - bold
                  - italic
                  - link
              - label: Contact
                name: contact
                widget: object
                fields:
                - {label: Caption, name: caption, widget: string}
                - label: Link
                  name: link
                  widget: object
                  fields:
                  - {label: Label, name: label, widget: string}
                  - {label: URL, name: url, widget: string}

      - label: Contact
        name: Contact
        file: 'static/content/contact.json'
        extension: json
        fields:
          - label: Meta
            name: meta
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Image, name: image, widget: image}
          - {label: Email, name: email, widget: string}
          - {label: Phone, name: phone, widget: string}
          - label: Address
            name: address
            widget: markdown
            buttons:
            - bold
            - italic
          - {label: Connect Label, name: connectLabel, widget: string}
          - {label: LinkedIn, name: linkedin, widget: string}
          - {label: Dribbble, name: dribbble, widget: string}
          - {label: Behance, name: behance, widget: string}
          - label: Resume
            required: false
            name: "resume"
            widget: "file"
          - label: Background Image
            name: backgroundImage
            widget: object
            fields:
            - {label: Image, name: src, widget: image}
            - {label: Alt Text, name: alt, widget: string}
          - label: Bold Page Title Text
            name: titleImage
            widget: object
            fields:
            - {label: Image, name: src, widget: image}
            - {label: Alt Text, name: alt, widget: string}

  - label: Work Detail Pages
    label_singular: Work Detail Page
    create: true
    folder: 'static/content/work'
    filter: {field: "type", value: "Obstacle, Objective, Outcome"}
    extension: json
    name: 'work-detail-pages'
    editor:
      preview: false
    fields:
      - {label: "Page Type", name: "type", widget: "select", options: ["Obstacle, Objective, Outcome", "Misc"], default: "Obstacle, Objective, Outcome"}
      - {label: "Title", name: "title", widget: "string"}
      - label: Images
        name: images
        widget: list
        allow_add: true
        field: {label: Image, name: image, widget: image}
      - {label: "Image Caption", name: "imageCaption", widget: "string"}
      - label: Bold Page Title Text
        name: titleImage
        widget: object
        fields:
        - {label: Image, name: src, widget: image}
        - {label: Alt Text, name: alt, widget: string}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Obstacle", name: "obstacle", widget: "text"}
      - {label: "Objective", name: "objective", widget: "text"}
      - {label: "Outcome", name: "outcome", widget: "text"}
      - label: Site Link
        name: siteLink
        widget: object
        fields:
        - {label: Label, name: label, widget: string}
        - {label: URL, name: url, widget: string}

  - label: Work Detail Pages - Misc
    label_singular: Work Detail Page - Misc
    create: true
    folder: 'static/content/work'
    filter: {field: "type", value: "Misc"}
    extension: json
    name: 'work-detail-pages-misc'
    editor:
      preview: false
    fields:
      - {label: "Page Type", name: "type", widget: "select", options: ["Obstacle, Objective, Outcome", "Misc"], default: "Misc"}
      - {label: "Title", name: "title", widget: "string"}
      - label: Images
        name: images
        widget: list
        allow_add: true
        field: {label: Image, name: image, widget: image}
      - {label: "Image Caption", name: "imageCaption", widget: "string"}
      - label: Bold Page Title Text
        name: titleImage
        widget: object
        fields:
        - {label: Image, name: src, widget: image}
        - {label: Alt Text, name: alt, widget: string}
      - {label: "Description", name: "description", widget: "string"}
      - label: Content
        name: richtext
        widget: markdown
        buttons:
        - heading-two
        - bold
        - italic
        - link
