---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: static/content/home.json
  label: Homepage
- type: document
  path: static/content/about.json
  label: About
- type: document
  path: static/content/work.json
  label: Work
  match: "**/*"
- type: directory
  path: static/content/work
  label: Work Detail
  create: documents
  match: "**/*"
  new_doc_ext: ".json"
- type: document
  path: static/content/contact.json
  label: Contact
  match: "**/*"
- type: heading
  label: Settings
- type: document
  path: static/content/menu.json
  label: Menu
  match: "**/*"
- type: document
  path: static/content/navbar.json
  label: Navbar
  match: "**/*"
- type: document
  path: static/content/social.json
  label: Social
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
