---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: static/content/home.json
  label: Homepage
- type: document
  path: static/content/about.json
  label: About
- type: document
  path: static/content/work.json
  label: Work
- type: directory
  path: static/content/work
  label: Work Detail
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - work-detail-misc
  - work-detail-standard
- type: document
  path: static/content/contact.json
  label: Contact
- type: heading
  label: Settings
- type: document
  path: static/content/menu.json
  label: Menu
- type: document
  path: static/content/navbar.json
  label: Navbar
- type: document
  path: static/content/social.json
  label: Social
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
  preview_command: vuepress build -d .vuepress/dist
